#pragma once
constexpr float MAP_LIMIT = 30.0f;
#include "PhysicsComponent.h"
#include "TransformComponent.h"
#include "MeshComponent.h"
#include "ColliderComponent.h"
#include "AIComponent.h"
#include "UnitComponent.h"
#include "SquadComponent.h"
#include "SquadMemberComponent.h"
#include "FactionComponent.h"
#include "StatComponent.h"
#include "FactoryComponent.h"
#include "GoldDepositComponent.h"
#include "GoldComponent.h"
#include "UIProgressBar.h"
#include "OccupyingDepositComponent.h"
#include "ParticleComponent.h"